# workflow name
name: CD-AWS (S3/EC2)
# workflow running trigger
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
# declare environment variables
env:
  AWS_REGION: "ap-northeast-2"
  PROJECT_NAME: "test_ci_cd"
  BUCKET_NAME: "developbeginner-s3-bucket"
  CODE_DEPLOY_APP_NAME: "cicdapp"
  CODE_DEPLOY_APP_GROUP: "cicdapp_deploy"
# set access scope for GITHUB_TOKEN
permissions:
  id-token: write
  contents: read
# workflow jobs
jobs:
  S3PackageUpload:
    # set runtime environment
    runs-on: ubuntu-latest
    steps:
      # checkout resources from $GITHUB_WORKSPACE
      - name: checkout resources
        uses: actions/checkout@v3
      # setup java development kit 17
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
      # grant permission for gradlew
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew
      # build gradle
      - name: Build with Gradle
        run: ./gradlew build
      # compress jar to zip file
      - name: Compress File
        run: zip -qq -r ./$GITHUB_SHA.zip .
      # configure credentials for AWS OIDC connection
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ env.AWS_REGION }}
      # upload to AWS S3 bucket
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
      # deploy to AWS EC2 Server
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtTime --deployment-group-name $CODE_DEPLOY_APP_GROUP --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
