# workflow name
name: CI
# workflow running trigger
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
# workflow jobs
jobs:
  build:
    # set runtime environment
    runs-on: ubuntu-latest
    steps:
      # checkout resources from $GITHUB_WORKSPACE
      - name: checkout resources
        uses: actions/checkout@v3
      # setup java development kit 17
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with: 
          java-version: "17"
          distribution: "corretto"
      # grant permission for gradlew
      - name: grant permission for gradlew
        run: chmod +x ./gradlew
      # build gradle
      - name: build gradle
        run: ./gradlew build
