# workflow 이름
name: CI

# workflow 실행 트리거
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# workflow 실행 작업
jobs:
  build:
    # 실행 환경
    runs-on: ubuntu-latest
    # 작업 순서
    steps:
      # 작업 활용에 필요한 리소스를 $GITHUB_WORKSPACE에서 체크아웃
      - uses: actions/checkout@v3
      # JDK 설정
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          java-version: "17"
          distribution: "Corretto"
      # gradlew에 실행 권한 부여 (+x)
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew
      # gradle 빌드
      - name: Build gradle
        run: ./gradlew build
