# workflow name
name: Test CD workflow
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
env:
  AWS_REGION: "ap-northeast-2"
  PROJECT_NAME: "test_ci_cd"
  BUCKET_NAME: "developbeginner-s3-bucket"
  CODE_DEPLOY_APP_NAME: "cicdapp"
  CODE_DEPLOY_APP_GROUP: "cicdapp_deploy"
permissions:
  id-token: write
  contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Compress File
        run: zip -qq -r ./$GITHUB_SHA.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtTime --deployment-group-name $CODE_DEPLOY_APP_NAME --s3-location bucket=BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
